from __future__ import annotations
from typing import Protocol, Optional, Dict, Any

class MachineIO(Protocol):
    """Interfaccia astratta per qualunque macchina (simulata o reale)."""

    # Stato movimento / posizione
    def get_position(self) -> Optional[float]: ...
    def is_positioning_active(self) -> bool: ...

    # Lettura ingressi logici (pulsanti / sensori)
    def get_input(self, name: str) -> bool: ...

    # Comandi principali
    def command_move(self, length_mm: float, ang_sx: float = 0.0, ang_dx: float = 0.0,
                     profile: str = "", element: str = "") -> bool: ...
    def command_lock_brake(self) -> bool: ...
    def command_release_brake(self) -> bool: ...
    def command_set_head_angles(self, sx: float, dx: float) -> bool: ...
    def command_set_pressers(self, left_locked: bool, right_locked: bool) -> bool: ...

    # Simulazioni (solo design mode)
    def command_sim_cut_pulse(self) -> None: ...
    def command_sim_start_pulse(self) -> None: ...
    def command_sim_dx_blade_out(self, on: bool) -> None: ...

    # Ciclo aggiornamento (tick)
    def tick(self) -> None: ...

    # Stato completo (diagnostica)
    def get_state(self) -> Dict[str, Any]: ...

    # Shutdown / cleanup
    def close(self) -> None: ...
