from typing import Protocol, Optional, Any, Dict

class MachineIO(Protocol):
    # Letture
    def get_position(self) -> Optional[float]: ...
    def is_positioning_active(self) -> bool: ...
    def get_input(self, name: str) -> bool: ...
    def get_state(self) -> Dict[str, Any]: ...

    # Comandi simulati / generici
    def move_to(self, length_mm: float, ang_sx: float = 0.0, ang_dx: float = 0.0,
                profile: str = "", element: str = "") -> None: ...
    def lock_brake(self) -> None: ...
    def release_brake(self) -> None: ...
    def set_presser(self, side: str, locked: bool) -> None: ...
    def simulate_cut_pulse(self) -> None: ...
    def simulate_start_press(self) -> None: ...
    def tick(self) -> None: ...
